" About syntax
syntax on

" About indent
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent

filetype plugin indent on
filetype indent on

" Delete by backspace
" :help 'backspace'
set backspace=2

augroup auto_mkdir
    autocmd!
    autocmd BufWritePre *
        \ if !isdirectory(expand("%:h")) |
        \   call mkdir(expand("%:h"), "p") |
        \ endif
augroup END

set laststatus=2
set statusline=%m%r%w\ %F\ \ %y\ %=\ \ %l/%L,\ %c\ %{&ff}

nnoremap <Space><Space> :%!<C-r>=input('Shell command: ')<CR><CR>
xnoremap <Space><Space> :!<C-r>=input('Shell command: ')<CR><CR>
