[ids]
*

[main]
capslock = layer(caps)

[caps]
f = right
b = left
p = up
n = down
a = home
e = end
h = backspace
d = delete
k = macro(S-end backspace)
u = macro(S-home backspace)
w = C-backspace
g = esc
slash = C-z
