[ids]
*

[main]
capslock = layer(caps)

[caps]
1 = back
2 = forward
3 = search
f = right
b = left
p = up
n = down
a = home
e = end
h = backspace
d = delete
k = macro(S-end backspace)
u = macro(S-home backspace)
w = C-x
y = S-insert
g = esc
s = C-f
slash = C-z
