#!/usr/bin/env bash
set -euo pipefail

_use_deepseek() {
  export ANTHROPIC_BASE_URL="https://api.deepseek.com/anthropic"
  export ANTHROPIC_AUTH_TOKEN="$DEEPSEEK_API_KEY"
  export ANTHROPIC_MODEL='deepseek-v4-flash'
  export ANTHROPIC_DEFAULT_OPUS_MODEL='deepseek-v4-flash'
  export ANTHROPIC_DEFAULT_SONNET_MODEL='deepseek-v4-flash'
  export ANTHROPIC_DEFAULT_HAIKU_MODEL=deepseek-v4-flash
  export CLAUDE_CODE_SUBAGENT_MODEL=deepseek-v4-flash
  export CLAUDE_CODE_EFFORT_LEVEL=max
}

_use_glm() {
  export ANTHROPIC_BASE_URL="https://open.bigmodel.cn/api/anthropic"
  export ANTHROPIC_AUTH_TOKEN="$GLM_API_KEY"
  export ANTHROPIC_MODEL=glm-5.1
  export ANTHROPIC_DEFAULT_OPUS_MODEL=glm-5.1
  export ANTHROPIC_DEFAULT_SONNET_MODEL=glm-4.7
  export ANTHROPIC_DEFAULT_HAIKU_MODEL=glm-4.7
  export CLAUDE_CODE_SUBAGENT_MODEL=glm-4.7
}

export API_TIMEOUT_MS="3000000"
export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1

PASSTHROUGH_ARGS=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --deepseek) _use_deepseek ;;
    --glm) _use_glm ;;
    *) PASSTHROUGH_ARGS+=("$1") ;;
  esac
  shift
done


claude "${PASSTHROUGH_ARGS[@]}"
