#!/usr/bin/env bash
set -euo pipefail

source ~/.profile.d/mitm-proxy.sh

_use_deepseek() {
    export ANTHROPIC_BASE_URL="https://api.deepseek.com/anthropic"
    export ANTHROPIC_AUTH_TOKEN="$(pass DEEPSEEK_API_KEY)"
    export ANTHROPIC_MODEL='deepseek-v4-pro'
    export ANTHROPIC_DEFAULT_OPUS_MODEL='deepseek-v4-pro'
    export ANTHROPIC_DEFAULT_SONNET_MODEL='deepseek-v4-pro'
    export ANTHROPIC_DEFAULT_HAIKU_MODEL=deepseek-v4-flash
    export CLAUDE_CODE_SUBAGENT_MODEL=deepseek-v4-flash
}

_use_glm() {
    export ANTHROPIC_BASE_URL="https://api.z.ai/api/anthropic"
    export ANTHROPIC_AUTH_TOKEN="$(pass GLM_API_KEY)"
    export ANTHROPIC_MODEL=glm-5.3
    export ANTHROPIC_DEFAULT_OPUS_MODEL=glm-5.3
    export ANTHROPIC_DEFAULT_SONNET_MODEL=glm-5.3
    export ANTHROPIC_DEFAULT_HAIKU_MODEL=glm-4.7
    export CLAUDE_CODE_SUBAGENT_MODEL=glm-4.7
}

export API_TIMEOUT_MS="3000000"
export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1
export CLAUDE_CODE_EFFORT_LEVEL=high

PASSTHROUGH_ARGS=()

while [[ $# -gt 0 ]]; do
    case "$1" in
	--deepseek) _use_deepseek ;;
	--glm) _use_glm ;;
	*) PASSTHROUGH_ARGS+=("$1") ;;
    esac
    shift
done

/usr/bin/claude "${PASSTHROUGH_ARGS[@]}" --allow-dangerously-skip-permissions
