#!/usr/bin/env bash

set -eu

ORI_FILE="$1"
TMP_FILE="${1}.clean-absent"

[ -f "$TMP_FILE" ] && rm "$TMP_FILE"

perl -lne 'print if !$seen{$_}++ && -d $_' "$ORI_FILE" > "$TMP_FILE"

mv "$ORI_FILE" "${ORI_FILE}.bak"
mv "$TMP_FILE" "$ORI_FILE"
