#!/usr/bin/env bash



pdump() {
    command emacs --batch \
      --eval '(package-initialize)' \
      -l ~/.emacs.d/init.el \
      --eval '(chin/dump)' 
}

emacs --dump-file="$HOME/.emacs.d/emacs.pdmp" "$@"
