#!/usr/bin/env bash

if [ "$1" = "--dump" ]; then
    command emacs --batch \
            --eval '(package-initialize)' \
            -l ~/.emacs.d/init.el \
            --eval '(chin/dump)'
    exit
fi

emacs --dump-file="$HOME/.emacs.d/emacs.pdmp" "$@"
