#!/usr/bin/env bash

export HTTPS_PROXY=http://127.0.0.1:9922
export https_proxy=http://127.0.0.1:9922
export HTTP_PROXY=http://127.0.0.1:9922
export http_proxy=http://127.0.0.1:9922
export NODE_EXTRA_CA_CERTS=/home/chin/.mitm-proxy/ca.pem
export SSL_CERT_FILE=/home/chin/.mitm-proxy/ca-bundle.pem
export REQUESTS_CA_BUNDLE=/home/chin/.mitm-proxy/ca-bundle.pem
export CURL_CA_BUNDLE=/home/chin/.mitm-proxy/ca-bundle.pem

/usr/bin/grok "$@"
