#!/usr/bin/env bash

export GIT_AUTHOR_NAME=OpenCode
export GIT_AUTHOR_EMAIL=noreply@opencode.ai

if [ -f ~/.llm.log/pid ] && [ -d /proc/$(cat ~/.llm.log/pid) ] ; then
  eval $(llm-log env)
fi

opencode "$@"
