#!/usr/bin/env bash

set -euo pipefail

IMAGE_FILE=""
OUTPUT=""
INTERVAL_SECONDS=100
ARGS=()

show_wall() {
    local image="$1"
    awww img \
         --resize crop \
         --transition-type push-right \
         --transition-duration 2 \
         "${ARGS[@]}" \
         "$image"

}

while [ $# -gt 0 ]; do
    case $1 in
        -o)
            shift
            ARGS+=("--outputs" "$1")
            ;;
        *)
            IMAGE_FILE="$1"
            ;;
    esac
    shift
done

if [ -z "$IMAGE_FILE" ]; then
    exit 1
elif [ -f "$IMAGE_FILE" ]; then
    show_wall "$IMAGE_FILE"
elif [ -d "$IMAGE_FILE" ]; then
    while true; do
        find "${IMAGE_FILE}" -type f | sort -R | while read image; do
            show_wall "$image"
            sleep "$INTERVAL_SECONDS"
        done
    done
fi
