#!/usr/bin/env bash

export OPENAI_API_KEY="sk-cpa"

codex -c model=deepseek-v4-pro \
  -c model_provider=cpa \
  -c model_providers.cpa.name=cpa  \
  -c model_providers.cpa.base_url=http://l25.lc:8317/v1 \
  -c model_providers.cpa.env_key="OPENAI_API_KEY" "$@"
